# Generated by Django 4.0.5 on 2022-06-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numTel', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomF', models.CharField(max_length=100)),
                ('prenomF', models.CharField(max_length=100)),
                ('numTelF', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(blank=True, choices=[('LG', 'Lg'), ('SAMSUNG', 'Samsung'), ('MontBlanc', 'Montblanc'), ('Condor', 'Condor'), ('BIOLUX', 'Biolux'), ('WHIRLPOOL', 'Whirlpool'), ('COALA', 'Coala')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('prix', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='GestionElectro/fichier/images')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetitProduit',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionElectro.produit')),
                ('couleur', models.CharField(blank=True, max_length=100)),
                ('capacite', models.FloatField(default=0)),
                ('puissance', models.FloatField(default=0)),
                ('fonctionAntiGoutte', models.CharField(blank=True, max_length=100)),
                ('Carafeetentonnoirlavables', models.CharField(blank=True, max_length=100)),
                ('Dispositifantichauffageàsec', models.CharField(blank=True, max_length=100)),
            ],
            bases=('GestionElectro.produit', models.Model),
        ),
    ]
