# Generated by Django 4.0.5 on 2022-06-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionElectro', '0002_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='GestionElectro.produit'),
        ),
    ]
